// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWygSP3iu1XBiYZEkGglx-8XBarnsmcvE',
    appId: '1:829093301668:web:a9d8b570e0074419240531',
    messagingSenderId: '829093301668',
    projectId: 'farmers-22',
    authDomain: 'farmers-22.firebaseapp.com',
    storageBucket: 'farmers-22.firebasestorage.app',
    measurementId: 'G-R7KJKLMK63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxOhYocpdomBDDZBRKtF-_Qvgp7Bn-3go',
    appId: '1:829093301668:android:f52ecbfda6cd8ed5240531',
    messagingSenderId: '829093301668',
    projectId: 'farmers-22',
    storageBucket: 'farmers-22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMRlkF794npW4dFeiV5zVZrXSCvxqDbM',
    appId: '1:829093301668:ios:5e9feb21d7f7a929240531',
    messagingSenderId: '829093301668',
    projectId: 'farmers-22',
    storageBucket: 'farmers-22.firebasestorage.app',
    iosClientId: '829093301668-hnscv7ea0dqla05lc01iec7eoh7u4iv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.laxman1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlMRlkF794npW4dFeiV5zVZrXSCvxqDbM',
    appId: '1:829093301668:ios:5e9feb21d7f7a929240531',
    messagingSenderId: '829093301668',
    projectId: 'farmers-22',
    storageBucket: 'farmers-22.firebasestorage.app',
    iosClientId: '829093301668-hnscv7ea0dqla05lc01iec7eoh7u4iv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.laxman1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWygSP3iu1XBiYZEkGglx-8XBarnsmcvE',
    appId: '1:829093301668:web:83e2c66b05dea8d8240531',
    messagingSenderId: '829093301668',
    projectId: 'farmers-22',
    authDomain: 'farmers-22.firebaseapp.com',
    storageBucket: 'farmers-22.firebasestorage.app',
    measurementId: 'G-3JN9FV731M',
  );

}